#pragma once

#ifndef DW_DECL_IMPORT
#  include <dwglobal.h>
#endif // DW_DECL_EXPORT

#ifdef BUILD_YYWIDGET_COMMON
#  define YYWIDGET_COMMON_EXPORT DW_DECL_EXPORT
#else
#  define YYWIDGET_COMMON_EXPORT DW_DECL_IMPORT
#endif // BUILD_YYWIDGETS_COMMON

#ifdef BUILD_YYWIDGET_CHANNEL
#  define YYWIDGET_CHANNEL_EXPORT DW_DECL_EXPORT
#else
#  define YYWIDGET_CHANNEL_EXPORT DW_DECL_IMPORT
#endif // BUILD_YYWIDGETS_COMMON
