#pragma once

#include "yymainframelogic/yydatareport_i.h"
#include "yymainframelogic/yylogin_i.h"
#include "yymainframelogic/yypiputility_i.h"
#include "yymainframelogic/yysystemmessage_i.h"
#include "yymainframelogic/yynotificationbox_i.h"
#include "yymainframelogic/yyaccountmanager_i.h"
#include "yymainframelogic/yycheckupdate_i.h"
#include "yymainframelogic/yywebloginticket_i.h"
#include "yymainframelogic/yyconfigroam_i.h"
#include "yymainframelogic/yychannelstatus_i.h"
#include "yymainframelogic/yyqchannellist_i.h"
#include "yymainframelogic/yylocalchannellist_i.h"
#include "yymainframelogic/yymultiaudiofileplayer_i.h"
#include "datacenter/yydatabase_i.h"
